const AIRPORT_NAMES: Record<string, string> = {
  ABE: "Lehigh Valley International Airport",
  AGP: "Malaga Airport",
  ASE: "Aspen/Pitkin County Airport",
  ATL: "Hartsfield-Jackson Atlanta International Airport",
  AUA: "Queen Beatrix International Airport",
  AVL: "Asheville Regional Airport",
  BOS: "Boston Logan International Airport",
  BTV: "Patrick Leahy Burlington International Airport",
  BWI: "Baltimore/Washington International Airport",
  BZN: "Bozeman Yellowstone International Airport",
  CDC: "Cedar City Regional Airport",
  CDG: "Paris Charles de Gaulle Airport",
  CHS: "Charleston International Airport",
  CLE: "Cleveland Hopkins International Airport",
  CLT: "Charlotte Douglas International Airport",
  CVG: "Cincinnati/Northern Kentucky International Airport",
  DAB: "Daytona Beach International Airport",
  DCA: "Ronald Reagan Washington National Airport",
  DEN: "Denver International Airport",
  DFW: "Dallas/Fort Worth International Airport",
  EDI: "Edinburgh Airport",
  EYW: "Key West International Airport",
  FAO: "Faro Airport",
  FCO: "Rome Fiumicino Airport",
  HER: "Heraklion International Airport",
  HND: "Tokyo Haneda Airport",
  HNL: "Daniel K. Inouye International Airport",
  IAH: "George Bush Intercontinental Airport",
  JAC: "Jackson Hole Airport",
  JFK: "John F. Kennedy International Airport",
  KOA: "Ellison Onizuka Kona International Airport",
  LAS: "Harry Reid International Airport",
  LAX: "Los Angeles International Airport",
  LIH: "Lihue Airport",
  LPA: "Gran Canaria Airport",
  MAH: "Menorca Airport",
  MAN: "Manchester Airport",
  MCI: "Kansas City International Airport",
  MCO: "Orlando International Airport",
  MDT: "Harrisburg International Airport",
  MIA: "Miami International Airport",
  MMH: "Mammoth Yosemite Airport",
  MSN: "Dane County Regional Airport",
  MSP: "Minneapolis-Saint Paul International Airport",
  MYR: "Myrtle Beach International Airport",
  NCE: "Nice Cote d'Azur Airport",
  OGG: "Kahului Airport",
  OKA: "Naha Airport",
  ORD: "Chicago O'Hare International Airport",
  ORF: "Norfolk International Airport",
  PHX: "Phoenix Sky Harbor International Airport",
  PSA: "Pisa International Airport",
  PSP: "Palm Springs International Airport",
  RNO: "Reno-Tahoe International Airport",
  RSW: "Southwest Florida International Airport",
  SAF: "Santa Fe Regional Airport",
  SAN: "San Diego International Airport",
  SAV: "Savannah/Hilton Head International Airport",
  SBP: "San Luis Obispo County Regional Airport",
  SEA: "Seattle-Tacoma International Airport",
  SFO: "San Francisco International Airport",
  SGF: "Springfield-Branson National Airport",
  SJD: "Los Cabos International Airport",
  SLC: "Salt Lake City International Airport",
  SBN: "South Bend International Airport",
  SXM: "Princess Juliana International Airport",
  SZG: "Salzburg Airport",
  TEX: "Telluride Regional Airport",
  TFS: "Tenerife South Airport",
  TUS: "Tucson International Airport",
  TVC: "Cherry Capital Airport",
  TYS: "McGhee Tyson Airport",
  VPS: "Destin-Fort Walton Beach Airport",
  YYC: "Calgary International Airport",
  YUL: "Montreal-Trudeau International Airport",
  YVR: "Vancouver International Airport",
  YYZ: "Toronto Pearson International Airport",
  ZIH: "Ixtapa-Zihuatanejo International Airport",
};

/** Rough IATA hints when CSV has no airport column */
const NAME_HINTS: { test: RegExp; iata: string }[] = [
  { test: /aruba|oranjestad/i, iata: "AUA" },
  { test: /schladming/i, iata: "SZG" },
  { test: /orlando/i, iata: "MCO" },
  { test: /kissimmee|winter garden/i, iata: "MCO" },
  { test: /vegas|las vegas/i, iata: "LAS" },
  { test: /miami|south beach|surfside/i, iata: "MIA" },
  { test: /daytona|ormond/i, iata: "DAB" },
  { test: /marathon/i, iata: "EYW" },
  { test: /naples, fl|naples fl/i, iata: "RSW" },
  { test: /sandestin/i, iata: "VPS" },
  { test: /myrtle/i, iata: "MYR" },
  { test: /honolulu|oahu|waikiki/i, iata: "HNL" },
  { test: /maui|lahaina|kaanapali/i, iata: "OGG" },
  { test: /kauai|lihue|koloa|poipu/i, iata: "LIH" },
  { test: /big island|kona|hilo|kohala|waikoloa/i, iata: "KOA" },
  { test: /park city|deer valley|salt lake/i, iata: "SLC" },
  { test: /brian head/i, iata: "CDC" },
  { test: /denver|breckenridge|keystone|vail|beaver/i, iata: "DEN" },
  { test: /aspen|snowmass/i, iata: "ASE" },
  { test: /tahoe|reno|truckee|incline/i, iata: "RNO" },
  { test: /mammoth/i, iata: "MMH" },
  { test: /jackson hole/i, iata: "JAC" },
  { test: /telluride/i, iata: "TEX" },
  { test: /big sky|bozeman/i, iata: "BZN" },
  { test: /whistler|vancouver/i, iata: "YVR" },
  { test: /panorama|banff|canmore/i, iata: "YYC" },
  { test: /tremblant|mont tremblant/i, iata: "YUL" },
  { test: /blue mountains|collingwood/i, iata: "YYZ" },
  { test: /ucluelet/i, iata: "YVR" },
  { test: /stowe|burlington/i, iata: "BTV" },
  { test: /new york|manhattan|nyc/i, iata: "JFK" },
  { test: /los angeles|\bla,?\s*(ca|california)\b/i, iata: "LAX" },
  { test: /san diego/i, iata: "SAN" },
  { test: /carlsbad|capistrano|garden grove/i, iata: "SAN" },
  { test: /palm springs|palm desert/i, iata: "PSP" },
  { test: /avila|pismo|san luis obispo/i, iata: "SBP" },
  { test: /manteca/i, iata: "SFO" },
  { test: /ramona/i, iata: "SAN" },
  { test: /san francisco|bay area/i, iata: "SFO" },
  { test: /seattle/i, iata: "SEA" },
  { test: /phoenix|scottsdale|sedona|cave creek/i, iata: "PHX" },
  { test: /payson|pinetop/i, iata: "PHX" },
  { test: /tucson/i, iata: "TUS" },
  { test: /washington,? dc|washington dc/i, iata: "DCA" },
  { test: /chicago|gurnee/i, iata: "ORD" },
  { test: /south bend/i, iata: "SBN" },
  { test: /devon|lancashire/i, iata: "MAN" },
  { test: /paris|vincennes/i, iata: "CDG" },
  { test: /mougins|cannes|nice/i, iata: "NCE" },
  { test: /crete/i, iata: "HER" },
  { test: /pisa|selvatelles/i, iata: "PSA" },
  { test: /soriano nel cimino|soriano/i, iata: "FCO" },
  { test: /odawara/i, iata: "HND" },
  { test: /okinawa|sesoko/i, iata: "OKA" },
  { test: /los cabos|cabo|baja california/i, iata: "SJD" },
  { test: /zihuatanejo/i, iata: "ZIH" },
  { test: /atlanta|lagrange/i, iata: "ATL" },
  { test: /charlotte|concord/i, iata: "CLT" },
  { test: /charleston/i, iata: "CHS" },
  { test: /hilton head/i, iata: "SAV" },
  { test: /virginia beach|williamsburg/i, iata: "ORF" },
  { test: /pigeon forge|gatlinburg/i, iata: "TYS" },
  { test: /dallas|grapevine/i, iata: "DFW" },
  { test: /houston|webster/i, iata: "IAH" },
  { test: /branson|ridgedale/i, iata: "SGF" },
  { test: /santa fe/i, iata: "SAF" },
  { test: /boston|fitchburg/i, iata: "BOS" },
  { test: /baltimore|perryville/i, iata: "BWI" },
  { test: /kansas city/i, iata: "MCI" },
  { test: /minneapolis|bloomington/i, iata: "MSP" },
  { test: /traverse city/i, iata: "TVC" },
  { test: /cincinnati|mason/i, iata: "CVG" },
  { test: /sandusky/i, iata: "CLE" },
  { test: /hershey/i, iata: "MDT" },
  { test: /pocono|scotrun/i, iata: "ABE" },
  { test: /algarve/i, iata: "FAO" },
  { test: /ballater|perthshire/i, iata: "EDI" },
  { test: /sint maarten|philipsburg/i, iata: "SXM" },
  { test: /balearic|menorca/i, iata: "MAH" },
  { test: /costa del sol/i, iata: "AGP" },
  { test: /gran canaria/i, iata: "LPA" },
  { test: /tenerife/i, iata: "TFS" },
  { test: /grand mound/i, iata: "SEA" },
  { test: /wisconsin dells/i, iata: "MSN" },
  { test: /banner elk|cashiers|sapphire/i, iata: "AVL" },
  { test: /kitty hawk/i, iata: "ORF" },
];

export function guessDestinationIata(name: string, location: string): string | null {
  const blob = `${name} ${location}`;
  for (const { test, iata } of NAME_HINTS) {
    if (test.test(blob)) return iata;
  }
  return null;
}

export function airportName(iata: string): string {
  return AIRPORT_NAMES[iata.toUpperCase()] ?? "Airport name unavailable";
}

export function googleFlightsUrl(params: {
  origin: string;
  destination: string;
  departDate: string;
  returnDate: string;
}): string {
  const { origin, destination, departDate, returnDate } = params;
  const o = origin.toUpperCase();
  const d = destination.toUpperCase();
  const q = `Flights from ${o} to ${d} on ${departDate} through ${returnDate}`;
  return `https://www.google.com/travel/flights?q=${encodeURIComponent(q)}`;
}
